//    GreenPressing POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://code.google.com/p/openbravocustom/
//
//    This file is part of GreenPressing POS.
//
//    GreenPressing POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    GreenPressing POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with GreenPressing POS.  If not, see <http://www.gnu.org/licenses/>.

//package com.openbravo.pos.ticket;
//
//import com.openbravo.data.loader.SerializerWrite;
//import com.openbravo.pos.forms.AppLocal;
//
//import com.openbravo.pos.forms.AppView;
//import java.awt.Component;
//import java.util.List;
//import com.openbravo.data.loader.QBFCompareEnum;
//import com.openbravo.format.Formats;
//import com.openbravo.basic.BasicException;
//import com.openbravo.data.gui.ListQBFModelNumber;
//import com.openbravo.data.gui.ComboBoxValModel;
//import com.openbravo.data.loader.Datas;
//import com.openbravo.data.loader.SentenceList;
//import com.openbravo.data.loader.SerializerWriteBasic;
//import com.openbravo.pos.forms.DataLogicSales;
//import com.openbravo.pos.reports.ReportEditorCreator;
//
//public class HostFilter extends javax.swing.JPanel implements ReportEditorCreator {
//
//    private SentenceList m_sentcat;
//    private ComboBoxValModel m_CategoryModel;
//
//    /** Creates new form JQBFProduct */
//    public HostFilter() {
//
//        initComponents();
//    }
//
//    public void init(AppView app) {
//
//        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSales");
//
//        // El modelo de categorias
//        m_sentcat = dlSales.getCategoriesList();
//        m_CategoryModel = new ComboBoxValModel();
//
//        m_jCboName.setModel(new ListQBFModelNumber());
//        m_jCboPriceBuy.setModel(new ListQBFModelNumber());
//        m_jCboPriceSell.setModel(new ListQBFModelNumber());
//    }
//
//    public void activate() throws BasicException {
//
//        List catlist = m_sentcat.list();
//        catlist.add(0, null);
//        m_CategoryModel = new ComboBoxValModel(catlist);
//        m_jCategory.setModel(m_CategoryModel);
//    }
//
//    public SerializerWrite getSerializerWrite() {
//        return new SerializerWriteBasic(
//                new Datas[] {Datas.OBJECT, Datas.STRING, Datas.OBJECT, Datas.DOUBLE, Datas.OBJECT, Datas.DOUBLE, Datas.OBJECT, Datas.STRING, Datas.OBJECT, Datas.STRING});
//    }
//
//    public Component getComponent() {
//        return this;
//    }
//
//    public Object createValue() throws BasicException {
//
//        if (m_jBarcode.getText() == null || m_jBarcode.getText().equals("")) {
//            // Filtro por formulario
//            return new Object[] {
//                m_jCboName.getSelectedItem(), m_jName.getText(),
//                m_jCboPriceBuy.getSelectedItem(), Formats.CURRENCY.parseValue(m_jPriceBuy.getText()),
//                m_jCboPriceSell.getSelectedItem(), Formats.CURRENCY.parseValue(m_jPriceSell.getText()),
//                m_CategoryModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS, m_CategoryModel.getSelectedKey(),
//                QBFCompareEnum.COMP_NONE, null
//            };
//        } else {
//            // Filtro por codigo de barras.
//            return new Object[] {
//                QBFCompareEnum.COMP_NONE, null,
//                QBFCompareEnum.COMP_NONE, null,
//                QBFCompareEnum.COMP_NONE, null,
//                QBFCompareEnum.COMP_NONE, null,
//                QBFCompareEnum.COMP_RE, "%" + m_jBarcode.getText() + "%"
//            };
//        }
//    }
//
//
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        m_jCboName = new javax.swing.JComboBox();
        m_jName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal.getIntString("label.byform"))); // NOI18N

        m_jCboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jCboNameActionPerformed(evt);
            }
        });

        jLabel2.setText(AppLocal.getIntString("label.prodname")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jCboName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(m_jCboName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/*
    private void m_jCboNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jCboNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jCboNameActionPerformed
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox m_jCboName;
    private javax.swing.JTextField m_jName;
    // End of variables declaration//GEN-END:variables
    
}
*/